### ISSUE TITLE
Week 13 Project Assignment Feedback

### ISSUE THREAD

**Issue by emily1129** [SOA-2022-Upstart-02/api_comfywings#10]
1. In your `presentation` folder, `representers` and `responses` are the two actually needed
2. Consider renaming your `secrets.example.yml` into `secrets_example.yml`
3. `_cache` folder is recommended to add in **gitignore**

**Comment by drainvers** [comment]
- Cleaned up presentation folder
- Renamed example secrets file to match spec
- _cache folder added to gitignore
