### ISSUE TITLE
Week 12 Project Assignment Feedback

### ISSUE THREAD

**Issue by emily1129** [SOA-2022-Upstart-02/api_comfywings#6]
1. Use `include Dry::Monads::Result::Mixin` when the Service Object has one step only.
https://github.com/SOA-2022-Upstart-02/api_comfywings/blob/2ccd7aa28d50114a29808306bfff68e8e3d707e2/app/application/services/retrieve_currencies.rb#L10-L18
https://github.com/SOA-2022-Upstart-02/api_comfywings/blob/2ccd7aa28d50114a29808306bfff68e8e3d707e2/app/application/services/search_airport.rb#L10-L19
2. `assets` under the presentation folder can be deleted.

**Comment by drainvers** [comment]
- Both service objects now use result mixins instead of transaction
- Assets folder now deleted
